### ISSUE TITLE
Remove deprecation for Symfony v5.3

### ISSUE THREAD

**Issue by lubo13** [code-tool/jaeger-client-symfony-bridge#19]
Hello, in Symfony v.5.3 your bridge trigger deprecation exception:

`Since symfony/http-kernel 5.3: "Symfony\Component\HttpKernel\Event\KernelEvent::isMasterRequest()" is deprecated, use "isMainRequest()" instead.`

Can you update to clear such deprecation, please?

Thank you

**Comment by andrew-demb** [comment]
Hello @lubo13 

Deprecations were resolved in #18, but new release are blocked until a new feature for span name generators will be finished with more covered use cases and manual tests in production (#16).

**Comment by lubo13** [comment]
Thanks @andrew-demb

**Comment by andrew-demb** [comment]
@lubo13 seems like `v3.6.0` has been released with fixes - https://packagist.org/packages/code-tool/jaeger-client-symfony-bridge#v3.6.0
