### ISSUE TITLE
Skip health check endpoint

### ISSUE THREAD

**Issue by greeflas** [code-tool/jaeger-client-symfony-bridge#9]
Hi! I have a question.
How can I skip from tracing health check or another endpoint? Does this bundle have some exceptions list for application routes to skip?

**Comment by allflame** [comment]
@greeflas Currently all the requests will be traced depending only on sampler strategy.
I'll keep an issue open and we'll look into adding this functionally shortly.

**Comment by greeflas** [comment]
@allflame ok, thank you.

**Comment by greeflas** [comment]
Hi @allflame!
Do you have any plans to start implementing this feature?

**Comment by allflame** [comment]
@greeflas Your issue is (sort of) solved. You can disable sampling based on the operation name.

Thanks @andrew-demb

**Comment by allflame** [comment]
If you'll still need a solution based on route names, please reopen it later
